export enum EntityActionType {
  GET_ENTITY = 'GET_ENTITY',
  CLEAR_ENTITY = 'CLEAR_ENTITY',
  CHANGE_SIZE = 'CHANGE_SIZE'
}

export enum CartActionType {
  CHANGE_VISIBILITY_CART = 'CHANGE_VISIBILITY_CART',
  ADD_TO_CART = 'ADD_TO_CART',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART'
}